import type { Metadata } from "next";
import { Schoolbell } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const schoolbell = Schoolbell({ subsets: ["latin"],weight:['400'] });

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal:React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={schoolbell.className}>
        <Header/>      
        <main>
          <div className="container">
            {children}
            {modal}
          </div>
        </main>
      </body>
    </html>
  );
}
