import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={inter.className}>
        <header>
          <Link href='/'>Home</Link>
          <Link href='/seasons'>Seasons</Link>
          <Link href='/characters'>Characters</Link>
          <Link href='/locations'>Locations</Link>
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
        {children}
        </main>
      </body>
    </html>
  );
}
